### ISSUE TITLE
permanently denied on location request

### ISSUE THREAD

**Issue by cleawrence** [hamurcuabi/BestPermissionUtil#1]
Hi!
good job for you library but i have some problems.
When i ask access fine and coarse location, when i choose accept permission only when i m using the apps the result state is permanently denied.......
Do you have an idea?

**Comment by hamurcuabi** [comment]
I will check that thanks for your good question😇

**Comment by hamurcuabi** [comment]
I think you have a mistake, I checked it but there wasnt any bug.
